version: 2.1

jobs:
  check_sbt:
    parameters:
      image:
        type: string
        default: 'cimg/openjdk:11.0'
        description: Image to use for checking SBT tool
    docker:
      - image: << parameters.image >>
    steps:
      - run:
          name: Check SBT information on << parameters.image >>
          command: |
            command -v sbt
            sbt sbtVersion

workflows:
  main:
    jobs:
      - check_sbt:
          matrix:
            parameters:
              image:
                - 'cimg/openjdk:11.0'
                - 'circleci/openjdk:11-jdk-buster'
